server {
    server_name dcbsas.com www.dcbsas.com 2.25.71.62 _;
    root /var/www/dcbsas;
    index index.html;

    location /evidencias/ {
        alias /opt/backend/public/evidencias/;
        add_header Access-Control-Allow-Origin "*";
        add_header Cache-Control "public, max-age=31536000";
    }

    location /api/ {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/dcbsas.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dcbsas.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = www.dcbsas.com) {
        return 301 https://$host$request_uri;
    }
    if ($host = dcbsas.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name dcbsas.com www.dcbsas.com 2.25.71.62 _;
    return 404;
}
